services:
  backend:
    build: ./backend
    container_name: aifocus-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/aifocus
      - PORT=5000
      - JWT_SECRET=337565da163aa22572d2ac67b866170c612edf1c121d00da
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    container_name: aifocus-frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
